### ISSUE TITLE
/push/device/create rewrites existing activationId-pushtoken pair

### ISSUE THREAD

**Issue by honzasmuk** [lime-company/powerauth-push-server#95]
1) There are 2 activations on single device.
2) User 1 sends his push token along with his activationid to /push/device/create - now he is able to receive notifications
3) User 2 sends his push token (the same one as for user 1 in step 2) along with his activationid to /push/device/create - now he is able to receive notifications. But record in push_device_registration for user 1's activationid is rewritten by this new one.

Problem is in io.getlime.push.controller.rest.PushDeviceController#createDevice - it searches for push_device_registration first by tokenid. If it is found then it is rewritten by new activationid.

As we send /push/device/create after every user login only the most recently logged user receives notifications.

**Comment by petrdvorak** [comment]
We concluded after some reasoning that this behavior is "as designed" - we should not keep a single push token (that is associated with [app,device] pair) in our database twice, since we would not be able to determine if the duplicity is caused by "other legitimate account", or "already removed account".

We suggest to register only the "master" activation for the push notifications as a workaround for a quick release. After that, we need to figure out how to pair the users (or rather various identities) on the server side under single activation ID (outside the push token), which would help resolve many different tasks (such as instant user account switching, etc.).
